AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReactAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: react-weather-app-${AWS::AccountId}-${AWS::Region}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ReactAppS3Bucket.Arn}/*"
